name: check code

on:
  push:
    branches: [main, master, dev]

  pull_request:
    branches: [main, master, dev]

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: install hatch
        run: pip install -U hatch

      - name: test codestyle
        run: hatch run lint:style

      - name: test typing
        run: hatch run lint:typing

      - name: run tests
        run: hatch run default:test
